config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

validates :title, presence: true
validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io:File.open(file_path), filename: 'default_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.introduction = "test-login"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resouce)
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_guest_user, only: [:create]
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book_show = Book.find(params[:id])
    @book = Book.new
    @user = @book_show.user
  end

  def edit
    book = Book.find(params[:id])
    unless book.user == current_user
      redirect_to books_path
    end
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_guest_user
    if current_user.guest_user?
      flash[:notice] = 'ゲストユーザーは投稿機能を利用できません。'
      flash[:notice2] = 'ユーザー登録してのご利用をお待ちしております。'
      redirect_to user_path(current_user)# , notice: 'ゲストユーザーは投稿機能を利用できません。'
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_indexbook.html.erb
<h2>Books</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
<% books.each do |books| %>
  <tbody>
  <tr>
    <td><%= link_to user_path(books.user) do %>
          <%= image_tag books.user.get_profile_image(80, 80) %>
        <% end %>
    </td>
    <td><%= link_to book_path(books) do %>
          <%= books.title %>
        <% end %>
    </td>
    <td><%= books.body %></td>
  </tr>
  </tbody>
<% end %>
</table>

app/views/books/_newbook.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>

<label for="book_title">Title</label>
<div class="form_field mb-3">
  <%= f.text_field :title, class: "book_title w-100 form-control border border-secondary rounded" %>
</div>

<label for="book_body">Opinion</label>
<div class="form_area mb-3">
  <%= f.text_area :body, class: "book_body w-100 form-control border border-secondary rounded" %>
</div>

<div class="form_button">
  <%= f.submit 'Create Book', class: "bg-success text-light border-0 rounded px-3 py-2" %>
</div>

<% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="col-sm-12 col-md-8 col-lg-5 mx-auto px-0">
  <h2>Editing Book</h2>
  <%= form_with model: @book do |f| %>
    <label class="w-100" for="title_field">Title</label>
    <div class="form_field mb-3">
      <%= f.text_field :title, class: "title_field w-100 form-control border border-secondary rounded" %>
    </div>
    
    <label class="w-100" for="body_field">Opinion</label>
    <div class="form_field mb-3">
      <%= f.text_area :body, class: "body_field w-100 form-control border border-secondary rounded" %>
    </div>
    
    <div class="form-button mb-3">
      <%= f.submit 'Update Book', class: "bg-success text-light border-0 rounded px-3 py-2" %>
    </div>
  <% end %>
  
    <%= link_to 'Show', book_path(@book) %><span> | </span>
    <%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<div class="col-md-12">
<% if @book.errors.any? %>
  <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
</div>
<div class="col-md-3">
  <%= render 'users/showuser', user: @user %>
  <%= render 'newbook', book: @book %>
</div>
<div class="col-md-8 offset-md-1">
  <%= render 'indexbook', books: @books %>
</div>

app/views/books/show.html.erb
  <div class="col-md-3">
    <%= render 'users/showuser', user: @user %>
    <%= render 'newbook', book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
      <tbody>
        <tr>
          <td><%= image_tag @book_show.user.get_profile_image(100, 100) %><br>
          <%= link_to user_path(@book_show.user) do %>
            <% @book_show.user.name %>
          <% end %>
          </td>
          <td>
          <%= link_to book_path(@book_show) do %>
            <% @book_show.title %>
          <% end %>
          </td>
          <td><%= @book_show.body %></td>
          <% if @book_show.user == current_user %>
            <td><%= link_to edit_book_path(@book_show), role: "button" do %>
              <button class="btn btn-primary bg-success border-0" type="submit">Edit</button>
                <% end %>
            </td>
            <td><%= link_to book_path(@book_show), role: "button", method: :delete, "data-confirm" => "本当に消しますか？" do %>
              <button class="btn btn-primary bg-danger border-0" type="submit">Destroy</button>
              <% end %>
            </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  

app/views/homes/about.html.erb
<div class="col-7 mx-auto text-center">
  <h1>Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!</h1>
</div>

app/views/homes/top.html.erb
<div class="col-11 col-sm-10 col-md-9 col-lg-8 col-xl-7 mx-auto">
  <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers </strong>!!</h1>
  <div class="top_introduction">
    <p>In <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>
  </div>
</div>

<div class="col-10 col-sm-9 col-md-8 col-lg-7 col-xl-6 mx-auto">
  <div class="link_to_guest_login">
    <%= link_to users_guest_sign_in_path, method: :post, role: "button" do %>
      <button class="btn btn-primary w-100 bg-secondary" type="submit">ゲストログイン（閲覧用）</button>
    <% end %>
  </div>
  
  <div class="link_to_login mt-3">
    <%= link_to new_user_session_path, role: "button" do %>
      <button class="btn btn-primary w-100 bg-info" type="submit">Log in</button>
    <% end %>
  </div>
  
  <div class="link_to_sign up mt-3">
    <%= link_to new_user_registration_path, role: "button" do %>
      <button class="btn btn-primary w-100 bg-success" type="submit">Sign up</button>
    <% end %>
  </div>
</div>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta charset="utf-8"
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/94091b4590.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div class="row px-5 d-flex align-items-center">
            <%= link_to root_path, class: "nav-link text-light mt-3 mb-3 ml-0" do %>
            <span class="home-top text-light">Bookers</span>
            <% end %>

            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">

              <ul class="navlist d-lg-flex ml-auto mb-0">
              <% if user_signed_in? %>
                <li class="list-item mb-2 m-lg-0">
                  <%= link_to user_path(current_user.id), class: "text_light nav-link" do %>
                  <i class="fa-solid fa-home text-light"></i><span class="text-light mr-3"> Home</span>
                  <% end %>
                </li>
                <li class="list-item my-2 m-lg-0">
                  <%= link_to users_path, class: "text_light nav-link" do %>
                    <i class="fa-solid fa-users text-light"></i><span class="text-light mr-3"> Users</span>
                  <% end %>
                </li>
                <li class="list-item my-2 m-lg-0">
                  <%= link_to books_path, class: "text_light nav-link" do %>
                    <i class="fa-solid fa-book-open text-light"></i><span class="text-light mr-3"> Books</span>
                  <% end %>
                </li>
                <li class="list-item mt-2 mb-3 m-lg-0">
                  <%= link_to destroy_user_session_path, class: "text_light nav-link", method: :delete do %>
                    <i class="fa-solid fa-sign-out-alt text-light"></i><span class="text-light"> Log out</span>
                  <% end %>
                </li>
              <% else %>
                <li class="list-item mb-2 m-lg-0">
                  <%= link_to root_path, class: "text_light nav-link" do %>
                    <i class="fa-solid fa-home text-light"></i><span class="text-light mr-3"> Home</span>
                  <% end %>
                </li>
                <li class="list-item my-2 m-lg-0">
                  <%= link_to home_about_path, class: "text_light nav-link" do %>
                    <i class="fa-solid fa-link text-light"></i><span class="text-light mr-3"> About</span>
                  <% end %>
                </li>
                <li class="list-item my-2 m-lg-0">
                  <%= link_to new_user_registration_path, class: "text_light nav-link" do %>
                    <i class="fa-solid fa-user-plus text-light"></i><span class="text-light mr-3"> Sign up</span>
                  <% end %>
                </li>
                <li class="list-item mt-2 mb-3 m-lg-0">
                  <%= link_to new_user_session_path, class: "text_light nav-link" do %>
                    <i class="fa-solid fa-solid fa-sign-in-alt text-light"></i><span class="text-light"> Log in</span>
                  <% end %>
                </li>
              <% end %>
              </ul>

            </div>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="notice">
        <%= flash[:notice] %><br>
        <%= flash[:notice2] %>
      </div>
      <div class="container mt-3 px-0">
        <div class="row">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer>
      <div class="container">
        <div class="row mt-4">
          <p class=" mx-auto my-3">CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_showuser.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table table-hover">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>
<% unless user.guest_user? %>
  <%= link_to edit_user_path(user), role: "button" do %>
    <button class="btn btn-primary w-100 bg-light text-secondary border border-secondary" type="submit"><i class="fa-solid fa-user-cog"></i></button>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="col-sm-12 col-md-8 col-lg-5 mx-auto px-0">
  <% if @user.errors.any? %>
    <h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  
<h2>User info</h2>

<%= form_with model: @user do |f| %>

  <label class="w-100" for="name_field">Name</label>
  <div class="form_field mb-3">
    <%= f.text_field :name, class: "name_field w-100 form-control border border-secondary rounded" %>
  </div>
  
  <label class="w-100" for="image_field">Image</label>
  <div class="form_field mb-3">
    <%= f.file_field :profile_image, class: "image_field", accept: "image/*" %>
  </div>
  
  <label for="introduction_field">Introduction</label>
  <div class="form_field mb-3">
    <%= f.text_area :introduction, class: "introduction_field w-100 form-control border border-secondary rounded" %>
  </div>
  
  <div class="form-button">
    <%= f.submit 'Update User', class: "bg-secondary text-light border-0 rounded px-3 py-2" %>
  </div>
  
<% end %>
</div>

app/views/users/index.html.erb
<div class="col-md-3">
  <%= render 'showuser', user: @user %>
  <%= render 'books/newbook', book: @book %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80, 80) %></td>
        <td><%= user.name %></td>
        <td>
          <%= link_to 'Show', user_path(user) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="col-md-3">
  <%= render 'showuser', user: @user %>
  <%= render 'books/newbook', book: @book %>
</div>
<div class="col-md-8 offset-md-1">
  <%= render 'books/indexbook', books: @books %>
</div>
<% if @user.errors.any? %>
  <h2><%= @user.errors.count %> error prohibited this obj from being saved:</h2>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>